services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=commerce'
      - 'MYSQL_PASSWORD='
      - 'MYSQL_ROOT_PASSWORD='
      - 'MYSQL_USER=root'
    ports:
      - '33061:3306'
