server:
  port: 8081

# Swagger
springdoc:
  cache:
    # 캐시 비활성화
    disabled: true
  swagger-ui:
    path: /commerce/swagger.html

spring:
  profiles:
    default: local

  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # redis
  data:
    redis:
      host: localhost
      port: 6389

  # kafka
  kafka:
    bootstrap-servers: localhost:9092  # Kafka 서버 주소
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

---

spring:
  config:
    activate:
      on-profile: test

  # DB
  datasource:
    url: jdbc:h2:mem:~/eCommerceApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # SQL
  sql:
    init:
      mode: never