# Swagger
springdoc:
  cache:
    # 캐시 비활성화
    disabled: true

spring:
  jpa:
    show-sql: true # SQL 쿼리 로그 출력
  profiles:
    hibernate:
      format_sql: true

management:
  tracing:
    enabled: false