@startuml
actor Client
participant "MyController" as C
participant "MyService" as S
participant "MyControllerAdvice" as CA

Client -> C: GET /resource
activate C

C -> S: fetchData()
activate S

S -> S: throws ResourceNotFoundException
deactivate S

activate CA
C -> CA: handle(ResourceNotFoundException)
CA -> Client: 404 Not Found
deactivate CA

deactivate C
@enduml